# Generated by Django 4.2.11 on 2024-06-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0012_alter_order_total_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_list',
            name='num',
            field=models.FloatField(default=1),
        ),
    ]
